{% set name = "msgpack" %}
{% set version = "1.0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 95c02b0e27e706e48d0e5426d1710ca78e0f0628d6e89d5b5a5b91a5f12274f3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - msgpack

about:
  home: The package home page
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "MessagePack serializer"
  doc_url: 
  dev_url: 

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48416
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - bkreider
